<a href="https://colab.research.google.com/github/rcruzalegui/natto-repo/blob/master/rcruzalegui_lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras
# Helper libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import fetch_openml
from sklearn.utils import check_random_state
from sklearn.model_selection import train_test_split

print(tf.__version__)

2.6.0


In [ ]:
fashion_mnist = tf.keras.datasets.fashion_mnist
data = tf.keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [ ]:
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

In [ ]:
train_images.shape

(60000, 28, 28)

In [ ]:
len(train_labels)

60000

In [ ]:
test_images.shape

(10000, 28, 28)

In [ ]:
len(test_labels)

10000

One way to examine the image is to check the range of the pixel values, it can range from 0 which is black to 255 which is white. 

In [ ]:
plt.figure()
plt.imshow(train_images[0])
plt.colorbar()
plt.grid(False)
plt.show()

TypeError: ignored

We need to scale the values down between 0 to 1 

In [ ]:
train_images = train_images / 255.0

test_images = test_images / 255.0

In [ ]:
plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(train_images[i], cmap=plt.cm.binary)
    plt.xlabel(class_names[train_labels[i]])
plt.show()

## New Model - Train - Compile - Neural Network Classification Model

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10)
])

Compile Model 

In [ ]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

Train the Model 

In [ ]:
model.fit(train_images, train_labels, epochs=50)

Evaluate Accuracy 

In [ ]:
test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

print('\nTest accuracy:', test_acc)

Changed Optimizer from Adam to SGD 

In [ ]:
model.compile(optimizer='sgd',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [ ]:
model.fit(train_images, train_labels, epochs=50)

In [ ]:
test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

print('\nTest accuracy:', test_acc)

## Random Forest and Naive Bayer 

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from skimage.transform import pyramid_gaussian
from sklearn.model_selection import train_test_split

In [ ]:
X, y = fetch_openml('Fashion-MNIST', version=1, return_X_y=True)

SCRUB

In [ ]:
# SCRUB
random_state = check_random_state(0)
permutation = random_state.permutation(X.shape[0])
X = X[permutation]
y = y[permutation]
X = X.reshape((X.shape[0], -1))

In [ ]:
# SCRUB - FOR TESTING USE SMALLER
train_samples = 60000

In [ ]:
# SCRUB - TEST / TRAIN SPLIT

X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=train_samples, test_size=10000)

### Random Forests

In [ ]:
# MODEL BUILD - RANDOM FORESTS

from sklearn.ensemble import RandomForestClassifier 
forest = RandomForestClassifier(n_estimators = 10)
forest.fit(X_train, y_train)
print('Score: ', forest.score(X_test, y_test))
predictions = forest.predict(X_test)

BAYES

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [ ]:
# MODEL

# Initialize our classifier
gnb = GaussianNB()

# Train our classifier
model = gnb.fit(X_train, y_train)

In [ ]:
# MODEL

# Make predictions
preds = gnb.predict(X_test)


In [ ]:
# MODEL
# Evaluate accuracy
print(accuracy_score(y_test, preds))

0.5874


In [ ]:
# INTERPRET
expected = y_test
predicted = preds
print(confusion_matrix(expected, predicted))

[[617  43  25 181  74   0  19   0  28   0]
 [  1 930  10  42   2   0   5   0   1   0]
 [  5   9 315  68 577   0  19   0  23   0]
 [  7 296   8 652  32   0  11   0   1   0]
 [  0  27  42 157 760   0   5   0   5   0]
 [  0   1   2   2   0 274   5 654  10  35]
 [109  25 126 221 450   0  38   0  44   0]
 [  0   0   0   0   0   7   0 980   4  10]
 [  1   1  30 101 156   2  19   4 678   1]
 [  0   0   1   0   0  18   4 352   8 630]]
